
env:
   global:
     - CONAN_REFERENCE: "OpenVDB/4.0.2"
     - CONAN_USERNAME: "kazuki"
     - CONAN_LOGIN_USERNAME: "kazuki"
     - CONAN_CHANNEL: "development"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/kazuki/conan"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

notifications:
  email: false
  slack:
    secure: "CtdLjx4HbkZfKHliEe/qm9RhpbKUexcc8C3pkAwksaBS0w982iHylZrlWDfm/5CTAUST9oVmnOhqUvg6VIjEH36xffjStSI3fkxiIWgbsAAra7Zl8st/H76SKtkq1ucSSbnbCqRaiX4Ag8tdaxT95Ebr92Az9bwmhQl2S8uRscX6+TkSwNCX9aDJZFa7qIME+QYMV3N4vMmgyYHCXAYfsrgNk/TSisNz+GqpcpPN2jTAcJYTXAXqkNLh9PJbc4NoNUwLEuoiAsCjPzFuQgsDY/F6g9gcF4yJnts9/YhlstcLXfkkFOm5+2knK5ULj+4VJZS0B0E8G/Cgmr9CMKXYpgQIAR8NytLRCQMmOr36a/FDhvlVg+U1SO+ubfvHNDQn9donyyv+elj35fO1cleRKgJ7IoA+siWKYEKGsbex065cptcg/vVahs+DavnZfK4k60Ofw/Fn4iDxaDPKw2AMkk8QhS97NTEB1JmH7mMw6qunQsgrp9OSyFGxrpeJj+RSgHRT6iK6Kv71qBUlvPh+ykfeFZELD1+JMjSjz7+5FqcIf2NcezmmdvSUJjZupS4EjDInkvugV2kvzrsKbwI7azXPR+/HFPYrXTgHpDzYFfgik3yuN3piCYmFwgb7WCM4+YQ0g55Zr5bTZpNM2rABTYomDpFbuGgagkX4Yb+LHiA="