build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "OpenVDB/4.0.2"
    CONAN_USERNAME: "zogi"
    CONAN_LOGIN_USERNAME: "zogi"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/zogi/conan-packages"
    CONAN_REMOTES: "https://api.bintray.com/conan/zogi/conan-packages"

    matrix:
       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
         CONAN_VISUAL_VERSIONS: 12
       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
         CONAN_VISUAL_VERSIONS: 14
       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
         CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory
  - conan remote add zogi-bintray https://api.bintray.com/conan/zogi/conan-packages
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
  - conan remote add blosc-bintray https://api.bintray.com/conan/blosc/Conan

test_script:
  - python build.py
